PREP(adoptAbandonedCivs);
PREP(doReverse);
PREP(deleteIfDamaged);
PREP(doCustomActivity);
PREP(doingCustomActivity);

PREP(doStop);
PREP(isStopped);
PREP(doCarryOn);

PREP(endCustomActivity);
PREP(findPositionOfInterest);
PREP(forceEmotionSpeed);
PREP(forcePanicSpeed);
PREP(handleAceUnconscious);
PREP(getGlobalCivs);

PREP(initCommonEventhandlers);
PREP(initConfig);
PREP(isInHouse);
PREP(overclockStateMachines);
PREP(reverse_abort);
PREP(reverse_internal_end);
PREP(reverse_internal_pfh);
PREP(reverse_internal_stopCondition);
// PREP(reverse.spec);
PREP(reverse);
PREP(sm_activities);
PREP(sm_activities_state_asOrdered_enter);
PREP(sm_activities_state_asOrdered_exit);
PREP(sm_activities_state_panic_enter);
PREP(sm_activities_state_panic_exit);
PREP(sm_activities_trans_business_panic_condition);
PREP(sm_business);
PREP(sm_business_state_rally_enter);
PREP(sm_emotions);
PREP(sm_panic);
PREP(sm_panic_state_flight_enter);
PREP(sm_panic_state_flight_loop);
PREP(sm_panic_state_hidden_enter);
PREP(sm_panic_state_hide_enter);
PREP(sm_panic_trans_hide_hidden_condition);
PREP(sm_panic_trans_hide_hidden_handler);
PREP(uid);
