PREP(addCycleWaypoint);
PREP(addFootsy);
PREP(initConfig);
PREP(sm_business);
PREP(sm_business_state_patrol_enter);
PREP(sm_business_state_patrol_exit);
PREP(sm_business_trans_rally_patrol_condition);
PREP(taskPatrolAddWaypoint);
PREP(taskPatrolFindWaypoint);
// PREP(taskPatrolFindWaypoints.spec);
PREP(taskPatrolFindWaypoints);
// PREP(taskPatrol.spec);
PREP(taskPatrol);
