PREP(aceInteractWrapper);
PREP(addCivInteractions);
PREP(addInteractEventHandlers);
PREP(aimedAtTarget);
PREP(checkHonkingOnCivilian);
PREP(checkWeaponOnCivilianPerception);
PREP(checkWeaponOnCivilianPointer);
// PREP(feelsAddressedByGesture.spec);
PREP(feelsAddressedByGesture);
PREP(handleAnimation);
PREP(handleGestureGo);
PREP(handleGestureStop);
PREP(interact_backUpAction);
PREP(interact_backUpCondition);
PREP(interact_carryOnAction);
PREP(interact_carryOnCondition);
PREP(isPlayerHonking);
