name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup HEMTT
        uses: arma-actions/hemtt@v1

      - name: Build Mod
        run: hemtt build

      - name: Rename build folder
        run: mv .hemttout/build .hemttout/@grad_civs

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: grad_civs.zip
          path: .hemttout/@*
          include-hidden-files: true 
